gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "#8aadf4" # Blue
      - bold
    inactiveBorderColor:
      - "#a5adcb" # Subtext0
    optionsTextColor:
      - "#8aadf4" # Blue
    selectedLineBgColor:
      - "#363a4f" # Surface0
    cherryPickedCommitBgColor:
      - "#494d64" # Surface1
    cherryPickedCommitFgColor:
      - "#8aadf4" # Blue
    unstagedChangesColor:
      - "#ed8796" # Red
    defaultFgColor:
      - "#cad3f5" # Text
    searchingActiveBorderColor:
      - "#eed49f" # Yellow
  authorColors:
    "*": "#b7bdf8" # Lavender
