# Catppuccin Latte (contrast-corrected) — i3 colors
set $base     #eff1f5
set $mantle   #e6e9ef
set $crust    #dce0e8
set $text     #4c4f69
set $subtext1 #5c5f77
set $surface0 #ccd0da
set $surface1 #bcc0cc
set $surface2 #acb0be
set $blue     #165eed
set $lavender #4b4dcd
set $teal     #00686a
set $green    #1e7800
set $yellow   #8c5500
set $peach    #ba4a00
set $red      #d20f39
set $mauve    #8838ef

# class                 border    bground   text      indicator   child_border
client.focused          $blue     $base     $text     $lavender   $blue
client.focused_inactive $surface1 $base     $subtext1 $surface1   $surface1
client.unfocused        $surface0 $mantle   $surface2 $surface0   $surface0
client.urgent           $red      $base     $text     $red        $red
client.placeholder      $base     $crust    $text     $base       $base
client.background       $base
